application: atm-backend
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.app
